### ISSUE TITLE
TypeError: compareComp is undefined

### ISSUE THREAD

**Issue by Nitrama** [CreateJS/TweenJS#100]
> <html>
	<head>
		<script type="text/javascript" src="createjs.min.js"></script>
		<script type="text/javascript" src="CSSPlugin.js"></script>
		<script>				
			function init() {
				createjs.CSSPlugin.install();
				canvas = document.createElement ("canvas")
				canvas.style.backgroundColor = "#000000";
				canvas.setAttribute("width" , "200px")
				canvas.setAttribute("height" ,"200px")
				canvas.id = "canvas"
				document.getElementById("body").appendChild (canvas);
				tween = createjs.Tween.get(canvas, { loop: false })
				tween.to({transform: "* rotate(90deg)"}, 1000) 
			}
		</script>
	</head>
	<body onload="init();" id="body">
	</body>
</html>

TypeError: compareComp is undefined     CSSPlugin.js:251:72
Error in parsing value for ‘transform’.  Declaration dropped.

**Comment by gskinner** [comment]
Good catch. I just pushed a fix for this.
