### ISSUE TITLE
Make a slot Effect

### ISSUE THREAD

**Issue by Cpin0312** [CreateJS/TweenJS#105]
i need to make a slot effect for my game like calculating Coin or other,

Is tweenJs support to do it. Sorry that i am still not enought understanding TweenJs.Thanks

**Comment by lannymcnie** [comment]
This site is for reporting issues with TweenJS. If you have specific challenges, I recommend posting to [StackOverflow](https://stackoverflow.com), and including specific details of what you are trying to do, along with any samples or code snippets you already have.

Cheers.
