### ISSUE TITLE
'override' property a bit problematic for haXers

### ISSUE THREAD

**Issue by septinite** [CreateJS/TweenJS#21]
the optional 'override' keyword for the Tween.get properties object causes some issues when using haXe (reserved word), making using TweenJS there a little clunky

may i suggest  'overwrite'?

**Comment by gskinner** [comment]
I know this was ages ago, but is this still an issue? If so, we could perhaps alias overwrite to override (I'd be hesitant to break the API by removing override entirely). Would that help?

**Comment by septinite** [comment]
We didn't end up pursuing haXe for javascript development much further, so no longer an issue afaik.
