### ISSUE TITLE
Safari viewport

### ISSUE THREAD

**Issue by nicolasdesle** [CreateJS/TweenJS#29]
Hi 

I made some animations with Tween JS in canvas, all running smoothly in Chrome and FF on a mac. 

In Safari however, when a part of the canvas gets clipped outside of the viewport, the animation starts staggering and becomes really slow.

Did anyone expercience this before? Oh yes, the canvas is really big, about 2500px in width.

Thanks

**Comment by gskinner** [comment]
This is not a TweenJS issue. Sounds like a Safari canvas issue (which may effect EaselJS - feel free to open an issue there if so).

**Comment by nicolasdesle** [comment]
Thanks Grant!
