### ISSUE TITLE
Complete event or similar on Timeline

### ISSUE THREAD

**Issue by lannymcnie** [CreateJS/TweenJS#44]
If possible, it would be handy to be able to get an event when a Timeline has completed all its tweens.

**Comment by gskinner** [comment]
Timeline now dispatches `change` and `complete` events.

**Comment by zur4ik** [comment]
@gskinner 
I tried `.on("complete", ...)` with no luck and in documentation there is only `change` event. Did I missed somethting?

**Comment by meleyal** [comment]
I also ran into the issue of the `complete` event not firing, any progress on this?
