### ISSUE TITLE
validate

### ISSUE THREAD

**Issue by henricavalcante** [CreateJS/TweenJS#60]
in this line:

```
MotionGuidePlugin.calc = function(data, ratio, target) {
		if(data._segments == undefined){ MotionGuidePlugin.validate(data); }
```

I can't found function 'validate' in MotionGuidePlugin object.

**Comment by lannymcnie** [comment]
This looks like it was not completely implemented. Typically the data comes from Flash Pro export, so I don't think we have run into any cases where this actually happens. 

In the short term, we will ensure that it errors properly (vs a random RTE) - and hopefully implement the `validate` method eventually.

Thanks for the report!

**Comment by henricavalcante** [comment]
@micaelsouza @danilothiago please follow this issue

**Comment by lannymcnie** [comment]
The RTE handling was added in October 2015. Closing this issue, since there is no plan to handle it differently.

**Comment by henricavalcante** [comment]
thanks. =)
