### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by scls19fr** [CreateJS/TweenJS#61]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with TweenJS. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable TweenJS on @Sourcegraph by going to https://sourcegraph.com/github.com/CreateJS/TweenJS and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by lannymcnie** [comment]
Interesting. I am a project maintainer (I have push access), but didn't see any options. Do I need to have admin rights or something?

**Comment by gskinner** [comment]
I had a quick look at this, but it requires that I give SourceGraph access to my email and private repositories, which I'm not really a fan of.

Feel free to reopen and provide a pitch on the value of enabling this. SourceGraph doesn't really communicate much on their site.
