### ISSUE TITLE
Tween the stroke of a circle 

### ISSUE THREAD

**Issue by MarcGodard** [CreateJS/TweenJS#62]
Is there a way to:

```Javascript
var circle = new createjs.Shape();
circle.graphics.setStrokeStyle(12);

createjs.Tween.get(circle, {override: true})
                        .to({
                            setStrokeStyle: 5
                        }, 2000, createjs.Ease.bounceOut)
```

I want to change the thickness of the circle.

**Comment by lannymcnie** [comment]
In EaselJS, this is super easy. All Graphics commands can be saved off, and edited. Here is a quick fiddle using your code: http://jsfiddle.net/lannymcnie/bg6446mb/ You can see the parameters in the EaselJS docs for each command. http://www.createjs.com/Docs/EaselJS/classes/Graphics.StrokeStyle.html

Here is an article on the Graphics commands: http://blog.createjs.com/new-command-approach-to-easeljs-graphics/

In version 0.7.1, the easiest approach is to just redraw the circle each frame.
http://jsfiddle.net/lannymcnie/bg6446mb/1/

**Comment by lannymcnie** [comment]
Note: Please post questions to StackOverflow instead. This list is meant for reporting issues. Thanks!
