### ISSUE TITLE
Document needs update.

### ISSUE THREAD

**Issue by micromaomao** [CreateJS/TweenJS#63]
[This](http://createjs.com/Docs/TweenJS/classes/Ease.html) document has a link to `spark table demo` which is point to http://www.createjs.com/#!/Demos/TweenJS/Spark-Table but it should be http://www.createjs.com/Demos/TweenJS/Tween_SparkTable in order to get to that demo.

**Comment by lannymcnie** [comment]
Thanks! This has been fixed and pushed to GitHub.
