### ISSUE TITLE
pause method doc confused

### ISSUE THREAD

**Issue by futurist** [CreateJS/TweenJS#65]
TweenJS Doc section of method pause:

>http://www.createjs.com/Docs/TweenJS/classes/Tween.html#method_pause

```
Parameters:

- tween Tween
The tween to play. If null, it pauses this tween.
```

Should `play` be ?
```
The tween to pause....
```

Just confused. Thanks.

**Comment by lannymcnie** [comment]
Thanks for the report. This has already been addressed in GitHub, and should get published to the site shortly.

**Comment by sebastianderossi** [comment]
Thank you for your email.

I will be away from the office with limited access to email from May 10th till May 28th.

For urgent inquiries, please email Michael Graves: michael@gskinner.com

Thanks!
    -- 
      
      .sig {
      	font-family: Verdana, Lucida, Arial, Helvetica, sans-serif;
		font-size: 11px;
		color:#666666;
      }
      Sebastian DeRossi 
        Developer / CreateJS - community evangelist 
        gskinner.com 
        t:@derossi_s
