### ISSUE TITLE
how to move backwards

### ISSUE THREAD

**Issue by JahlomP** [CreateJS/TweenJS#68]
I have a shape I have moved on the x axis from 0 to 20. How do i move it backwards? i.e.move it on the x axis from 20 to 0.

**Comment by lannymcnie** [comment]
This is not an issue with the library. Please post future questions to StackOverflow, or other programming forums.

TweenJS just tweens between the numbers.  If you tween from 20 to 0, it will have the desired effect.

```javascript
shapeInstance.x = 20;
createjs.Tween.get(shapeInstance).to({x:0}, 5000);
```

Cheers.
