### ISSUE TITLE
What is the relationship between tween.js and easel.js?

### ISSUE THREAD

**Issue by Voyga** [CreateJS/TweenJS#69]

**Comment by lannymcnie** [comment]
TweenJS and EaselJS are both part of the CreateJS suite. They can each be used separately, with no dependencies, but they can also be used together. For example, the EaselJS MovieClip uses TweenJS for animation, and both use the same Ticker class, inheritance and event models, as well as a number of utilities. They are built to work together nicely.

**Comment by Voyga** [comment]
Thanks for explaining!
