### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by thomasklein** [CreateJS/TweenJS#70]
Hi guys,

which browsers are not supported by TweenJS?

**Comment by lannymcnie** [comment]
All modern browsers. The current cut-off is IE9+. For earlier versions, you can use TweenJS version 0.5.1 or below. The inheritance model was upgraded for version 0.6.0, which no longer supports IE8 and earlier.

**Comment by thomasklein** [comment]
Thanks man! Is that somewhere written as I didn't find it.

**Comment by lannymcnie** [comment]
Its actually out of date in the docs. Thanks for the reminder, we will update it. All libraries should have a browser support section on their main page (http://www.createjs.com/docs/tweenjs/modules/TweenJS.html)
