### ISSUE TITLE
'set' is unused in queue

### ISSUE THREAD

**Issue by RockyF** [CreateJS/TweenJS#82]
```js
target.x = 0;
createjs.Tween.get(target)
	.set({x: 100}, highlight)
	.to({x: 300}, 1500);
```

you should saw target move from 0 nor 100 (set({x: 100}))

**Comment by lannymcnie** [comment]
The set method won't work like that. Tweens will use their initial and `to()` values -- so if you are already using the `to()` method to change the `x` property, it will ignore the values set on it.

Change the `set` call to a `to` call with 0 duration.

```js
createjs.Tween.get(target)
    .to({x: 100})
    .to({x: 300}, 1500);
```

**Comment by RockyF** [comment]
ok, it is!
