### ISSUE TITLE
Simple method that will tells us if Tween is playing right now or not.

### ISSUE THREAD

**Issue by griii2** [CreateJS/TweenJS#84]
Surprisingly there is no simple isPlaying() : boolean method. Or am I missing something?

**Comment by lannymcnie** [comment]
There is currently no API for that. You can determine when a tween has finished by calling a method at the end of the chain:

```js
createjs.Tween({x:0}).to({x:100}).call(handleComplete);
```

Or you could query the tween's `duration` and `position` any time. When they are equal, the tween should be complete.

```js
var complete = (tween.position==tween.duration);
```

A boolean property is a good idea, so I will leave this issue open to track it!

**Comment by gskinner** [comment]
I'm looking at changing `setPaused` into a getter/setter, so you could query `paused`. Tweens are automatically paused when they reach their end.

Would that meet your needs?

**Comment by gskinner** [comment]
Added `paused`. Closing this. Let me know if it doesn't do what you need.

**Comment by griii2** [comment]
Perfect. Thanks.
