### ISSUE TITLE
Tween.call is called before the previous action really ended, on oChange event will be called after "call"

### ISSUE THREAD

**Issue by griii2** [CreateJS/TweenJS#85]
I have 

``` js
createjs.Tween.get(myShape,{onChange:update)}).to({x : 100}, 2000, createjs.Ease.quartInOut).call(ended);
```

one more update will be called after ended :(

**Comment by griii2** [comment]
A workaround: this is how you identify the last onChange event so that you can use it instead of the call function.

createjs.Tween.get(myShape,{onChange:update)}).to({x : 100}, 2000, createjs.Ease.quartInOut).call(ended);

function update(evt) {
evt.target.duration == evt.target.position
}

**Comment by gskinner** [comment]
This is expected behavior. The `change` event is triggered after each tick is resolved, which includes both property updates and action execution. If you want to tie some code into the VERY end of the tween, then use the `complete` event.

I've updated the documentation to make this more clear.

**Comment by griii2** [comment]
I understand. Once you update the documentation there should be no confusion. Thanks.

**Comment by gskinner** [comment]
The docs for `change` were updated to:
Dispatched whenever the tween's position changes. It occurs after all tweened properties are updated and actions are executed.
