### ISSUE TITLE
CSSPlugin missing from source 

### ISSUE THREAD

**Issue by gmattie** [CreateJS/TweenJS#90]
Neither the v0.6.2 combined nor minified source code for TweenJS contain a reference to a CSSPlugin.  [According to the documentation](http://www.createjs.com/docs/tweenjs/classes/CSSPlugin.html) the CSSPlugin should be installed just like the [MotionGuidePlugin](http://www.createjs.com/docs/tweenjs/classes/MotionGuidePlugin.html), which is present in v0.6.2:

`createjs.CSSPlugin.install(); //fails`
`createjs.MotionGuidePlugin.install(); //succeeds`

Since the CSSPlugin object is undefined it can not be installed.

**Comment by lannymcnie** [comment]
This is by design. The CSSPlugin is more of an example usage, and only has basic CSS capabilities. 

From the docs:
> Please note that the CSS Plugin is not included in the TweenJS minified file.

You need to include the CSSPlugin from GitHub yourself to use it.

Cheers,
