### ISSUE TITLE
Tick listener and GetContext Error

### ISSUE THREAD

**Issue by ratuspro** [CreateJS/TweenJS#93]
I'm using TweenJS and EaselJs installed using _bower_. I've encountered a problem recently where it seems the tick listener is calling the procedure this.canvas.getContext several times prompting this error:

![image](https://cloud.githubusercontent.com/assets/5813765/23518701/3e5c0ad4-ff6c-11e6-86ed-71ef84762c24.png)

Any suggestion?

**Comment by lannymcnie** [comment]
Sounds like the canvas is not null, but it has no context. What have you passed to the Stage as a canvas reference?

**Comment by ratuspro** [comment]
I've passed a canvas element. I'm trying to figure out what happened since I was able to run the code without errors in a different context. I think it has something to do with the canvas element not having a width or a height specified in html.

**Comment by lannymcnie** [comment]
Pretty sure a 0-size canvas still has a context. Can you provide a fiddle or something?

**Comment by gskinner** [comment]
A canvas tag without a context uses a default width / height (300 x 150), so that shouldn't be an issue. As Lanny mentioned though, the error you're getting would strongly indicate you may be passing in the wrong tag or something.

**Comment by gskinner** [comment]
Closing. Feel free to reopen if this is still an issue and more info is available.
