### ISSUE TITLE
Documentation: Tween.addLabel() should be Tween.label()

### ISSUE THREAD

**Issue by FumioNonaka** [CreateJS/TweenJS#99]
https://github.com/CreateJS/TweenJS/blob/6a571a92a68e511d122085df2d64c0b0eb276353/src/tweenjs/Tween.js#L520
Tween.label() method calls AbstractTween.addLabel().
http://createjs.com/docs/tweenjs/classes/Tween.html#method_addLabel

**Comment by lannymcnie** [comment]
Thanks! Fixed and pushed. Online docs and zips are not updated, but will be during the next build.
